TheBigLoad/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^loadboard/', include('loadboard.urls')),
]

loadboard/urls.py
#this is the url page that holds all urls for the loadboard section
#planning for various urls user can navigate to from the loadboard area

from django.conf.urls import url
from . import views

#this specifies which url page to look at from the html pages
app_name = 'loadboard'

urlpatterns = [
    # /loadboard/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /loadboard/71/
    #Note: the ?P below is basically how you use pass parameter of company_table_id
    url(r'^(?P<companyId>[0-9]+)/$', views.ViewCompanyDetails, name='detail'),

    # /loadboard/company/add/
    url(r'company/add/$', views.CompanyCreate.as_view(), name='company-add'),

    # /loadboard/company/#/
    url(r'company/(?P<companyId>[0-9]+)/$', views.CompanyUpdate.as_view(), name='company-update'),

    # /loadboard/company/#/delete/
    url(r'company/(?P<companyId>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name='company-delete'),

]

loadboard/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
#blue print for our database

class Company_table(models.Model):
    CompanyName = models.CharField(max_length=128)
    Address = models.CharField(max_length=1024)
    CreditScore = models.IntegerField(max_length=4)
    CompanyLogo = models.CharField(max_length=1024,null=True)

    def get_absolute_url(self):
        return reverse('loadboard:detail', kwargs={'companyId': self.pk})

    def __str__(self):
        return self.CompanyName

class Loadboard_table(models.Model):
    CompanyName = models.ForeignKey(Company_table, on_delete=models.CASCADE)
    Origin = models.CharField(max_length=128)
    Destination = models.CharField(max_length=128)
    Email = models.CharField(max_length=256)

    def __str__(self):
        return self.Origin + ' to ' + self.Destination

    def get_absolute_url(self):
        return reverse('loadboard:detail', kwargs={'pk': self.pk})

loadboard/views.py
from django.views import generic
from django.shortcuts import render
from .models import Company_table, Loadboard_table
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class IndexView(generic.ListView):
    template_name = 'loadboard/index.html'  # the variable contains which html file this view should point to
    context_object_name = 'all_loadboard'  # this variable contains the items from the 'get_queryset(self)' function

    def get_queryset(self):
        return Loadboard_table.objects.all()  # queries a list into variable 'context_object_name' variable above

def ViewCompanyDetails(request, companyId):
    CompanyObject = Company_table.objects.get(id=companyId)
    context = {'Company': CompanyObject,}
    return render(request, 'loadboard/detail.html', context)


class CompanyCreate(CreateView):
    model = Company_table
    fields = ['CompanyName', 'Address', 'CreditScore', 'CompanyLogo']

class CompanyUpdate(UpdateView):
    model = Company_table
    fields = ['CompanyName', 'Address', 'CreditScore', 'CompanyLogo']

class CompanyDelete(DeleteView):
    model = Company_table
    success_url = reverse_lazy('loadboard:index')

loadboard/templates/loadboard/Loadboard_table_form.html
<!DOCTYPE html>
{% extends 'loadboard/base.html' %}
{% block title %}Add a new load{% endblock %}


{% block body %}
    <div class = "row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf token %}
                        {% include 'loadboard/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

loadboard/templates/loadboard/base.html
<!DOCTYPE html>
<html lang="en">
<!-- Loads the path to your static files -->
{% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel = "stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'loadboard/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <head>
        <!-- The tab title -->
        <meta charset="UTF-8">
        <title> {% block title %}The Big Load{% endblock %}</title>
    </head>

    <body>
            <!-- Contains the top navbar -->
        <nav class="navbar navbar-inverse">
                <div class="container-fluid">

                    <!-- Nav Bar toggle that displays after browser collapse past a certain size -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'loadboard:index' %}">TheBigLoad</a>
                    </div>

                    <!-- Items -->
                    <div class="collapse navbar-collapse" id="topNavBar">

                        <ul class ="nav navbar-nav">
                            <li class="">
                                <a href="{% url 'loadboard:index' %}">
                                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; My Loadboard
                                </a>
                            </li>
                        </ul>

                        <form class="navbar-form navbar-left" role="search" method="get" action="#">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q">
                            </div>
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        </form>

                        <ul class="nav navbar-nav navbar-right">

                            <li class="">
                                <a href="{% url 'loadboard:company-add' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Company
                                </a>
                            </li>

                            <li class="">
                                <a href=""> About</a>
                            </li>

                            <li class="">
                                <a href="{% url 'loadboard:index' %}">
                                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Log Out
                                </a>
                            </li>
                        </ul>

                    </div>

                </div>
            </nav>
        {% block body %}
        {% endblock %}
    </body>

</html>

loadboard/templates/loadboard/company_table_form.html
{% extends 'loadboard/base.html' %}
{% block title %}Add a new Company{% endblock %}


{% block body %}
<div class ="container-fluid">

    <div class = "row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'loadboard/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

loadboard/templates/loadboard/detail.html
{% extends 'loadboard/base.html' %}

<head>
    <title>{% block title %}{{Company.CompanyName}}'s loadboard{% endblock %}</title>
</head>


<body>
    {% block body %}
        <h1> {{Company.CompanyName}} </h1>
        <h4>Credit Score: {{Company.CreditScore}}</h4>

            {% for lb in Company.loadboards_table_set.all %}
                <input type="radio" id="lb{{ forloop.counter }}" name="lb" value="{{ lb.id }}" />
                <label for="lb{{ forloop.counter }}">
                    {{ lb.Origin }} ---> {{lb.Destination}}
                </label><br>
            {% endfor %}
    {% endblock %}
</body>

loadboard/templates/loadboard/form-template.html
{% for field in form %}
    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

loadboard/templates/loadboard/index.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}
<head>

  <title>The Big Load - Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'loadboard/style.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">The Big Load</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about">ABOUT</a></li>
        <li><a href="#signup">SIGN UP</a></li>
        <li><a href="#contact">CONTACT</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron text-center">
  <h1>The Big Load</h1>
  <p>Your source for the biggest & juiciest loads!</p>
</div>

<!-- Container (About Section) -->
<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h2>About</h2><br>
      <p>This site is an attempt to be the hub where all dispatchers, brokers, and trucker like people get to congregate and talk about loads. Whether you are a company or individual who wants to post loads here, or whether you are a trucker out to find the optimal load/route, this will be your source.</p>
      <br><button class="btn btn-default btn-lg">Sneak a peek</button>
    </div>
    <div class="col-sm-2 offset-sm-2">
        <span class="glyphicon glyphicon-list-alt logo"></span>
    </div>
  </div>
</div>


<!-- Container (Sign Up Section) -->
<div id="signup" class="container-fluid bg-grey">
  <div class="text-center">
    <h2>Pricing</h2>
    <h4>Best part about The Big Load is it is completely free!</h4>
  </div>

  <div class="row slideanim">
    <div class="col-sm-4 col-sm-offset-2">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1>Dispatcher</h1>
        </div>
        <div class="panel-body">
           <p><strong>Use of load board</strong></p>
           <p><strong>Create your account</strong></p>
           <p><strong>Search for loads</strong></p>
        </div>
        <div class="panel-footer">
          <h3>$0</h3>
          <h4>per month</h4>
          <button class="btn btn-lg">Sign Up</button>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1>Poster</h1>
        </div>
        <div class="panel-body">
           <p><strong>Use of load board</strong></p>
           <p><strong>Create your account</strong></p>
           <p><strong>Post your loads</strong></p>
        </div>
        <div class="panel-footer">
          <h3>$0</h3>
          <h4>per month</h4>
          <button class="btn btn-lg">Sign Up</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Container (Contact Section) -->
<div id="contact" class="container-fluid">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Chicago, US</p>
      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
      <p><span class="glyphicon glyphicon-envelope"></span> myemail@something.com</p>
    </div>
    <div class="col-sm-7 slideanim">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>
</div>


<footer class="container-fluid bg-grey text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>The Big Load Logistics © Copyright 2017 - All rights reserved. All trademarks are the property of respective owners.</p>
</footer>

<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });

  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>

</body>
</html>

loadboard/templates/loadboard/loadboard.html
{% extends 'loadboard/base.html' %}

{% block body %}

    <table class="table-condensed table-bordered table-hover" style="width:60%" align="center">
            <thead class="thead-inverse">
                <tr>
                    <th>Company Name</th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Email</th>
                </tr>
            </thead>

        {% for item in all_loadboard %}

            <tbody>

                <tr>

                    <td>
                        <a href="{% url 'loadboard:detail' item.CompanyName_id %}">{{item.CompanyName}}</a>
                    </td>
                    <td>
                        <a href="{% url 'loadboard:detail' item.CompanyName_id %}">{{item.Origin}}</a>
                    </td>
                    <td>
                        <a href="{% url 'loadboard:detail' item.CompanyName_id %}">{{item.Destination}}</a>
                    </td>
                    <td>
                        <a href="{% url 'loadboard:detail' item.CompanyName_id %}">{{item.Email}}</a>
                    </td>
                </tr>
            </tbody>
       {% endfor %}
    </table>
{% endblock %}